name: mfa_mini_demo_bloc
description: Demo MFA (SMS) con estructura BLoC
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 2.32.0
  firebase_auth: 4.17.8
  cloud_firestore: 4.15.9
  flutter_bloc: 8.1.6
  equatable: 2.0.5

dependency_overrides:
  # MantÃ©n solo estos para resolver el tema PromiseJsImpl/handleThenable
  js: 0.6.7
  web: 0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
